FlaskAnuies/app.py
from flask import Flask
from routes.probabilidades import probabilidades_bp

app = Flask(__name__)
app.secret_key = 'default_secret_key'

# Registrar los blueprints
app.register_blueprint(probabilidades_bp)

@app.route('/')
def home():
    return "Welcome to the home page!"

if __name__ == '__main__':
    app.run(debug=True)

FlaskAnuies/routes/probabilidades.py
from flask import Blueprint, render_template

probabilidades_bp = Blueprint('probabilidades', __name__)

@probabilidades_bp.route('/ProbabilidadMedia')
def Media():
    return render_template('probabilidadmedia.html')

@probabilidades_bp.route('/ProbabilidadAlta')
def Alta():
    return render_template('probabilidadalta.html')

@probabilidades_bp.route('/ProbabilidadBaja')
def Baja():
    return render_template('probabilidadBaja.html')

@probabilidades_bp.route('/Mapa')
def Mapa():
    return render_template('MapaView.html')

@probabilidades_bp.route('/RA')
def RA():
    return render_template('RA.html')

@probabilidades_bp.route('/Danger')
def Danger():
    return render_template('Danger.html')

FlaskAnuies/templates/Danger.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AquAlert - Alerta de Inundación</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #FF0000;
            color: white;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: space-between;
            height: 100vh;
            text-align: center;
        }
        .alert-icon {
            margin-top: 20px;
            font-size: 40px;
        }
        .main-content {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            flex-grow: 1;
        }
        h1 {
            font-size: 24px;
            margin-bottom: 20px;
        }
        .alert-title {
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 20px;
        }
        p {
            font-size: 18px;
            margin-bottom: 10px;
        }
        .footer {
            font-size: 14px;
            margin-bottom: 20px;
        }
        .button-container {
            display: flex;
            flex-direction: column;
            gap: 20px;
            margin-top: 20px;
            width: 80%;
        }
        .button {
            background-color: white;
            color: #FF0000;
            border: none;
            padding: 10px 20px;
            font-size: 18px;
            border-radius: 5px;
            cursor: pointer;
            width: 100%;
            box-sizing: border-box;
        }
    </style>
</head>
<body>
    <div class="alert-icon">⚠️</div>
    <div class="main-content">
        <h1>Dirígete a una zona elevada y conserva la calma</h1>
        <div class="alert-title">ALERTA DE INUNDACIÓN</div>
        <p>Prepárate para una inundación inminente en un día en:</p>
        <p><strong>Valle de Bravo, Estado de México</strong></p>
    </div>
    <div class="footer">
        AquAlert App
        <br>
        Aviso sujeto a actualizaciones
    </div>
    <div class="button-container">
        <button class="button" data-url="{{ url_for('probabilidades.Mapa') }}" onclick="navigateTo(this)">Zonas Seguras</button>
        <button class="button" data-url="{{ url_for('probabilidades.RA') }}" onclick="navigateTo(this)">RA</button>
    </div>
    <script>
        function navigateTo(element) {
            const url = element.getAttribute('data-url');
            window.location.href = url;
        }
    </script>
</body>
</html>

FlaskAnuies/templates/MapaView.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AquAlert - Mapa de Puntos de Reunión</title>
    <link rel="stylesheet" href="../static/css/MapaEstilo.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script>
        function navigateTo(element) {
            const url = element.getAttribute('data-url');
            window.location.href = url;
        }
    </script>
    
</head>
<body>
    <div class="app-header">
        <i class="fas fa-tint"></i>
        AquAlert
    </div>
    <div id="map"></div>
    <div class="footer">
        <div class="nav-item" data-url="{{ url_for('probabilidades.Baja') }}" onclick="navigateTo(this)">
            <i class="fas fa-home"></i>
            <div>Home</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.Mapa') }}" onclick="navigateTo(this)">
            <i class="fas fa-map-marker-alt"></i>
            <div>Maps</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.RA') }}" onclick="navigateTo(this)">
            <i class="fas fa-chart-bar"></i>
            <div>RA</div>
        </div>
    </div>
    
    <script src="../static/js/mapa.js"></script>
</body>
</html>

FlaskAnuies/templates/RA.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AquAlert - Vista RA</title>
    <link rel="stylesheet" href="../static/css/RA.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    <script>
        function navigateTo(element) {
            const url = element.getAttribute('data-url');
            window.location.href = url;
        }
    </script>
    
</head>
<body>
    <div class="app-header">
        <i class="fas fa-tint"></i>
        AquAlert
    </div>
    <div class="video-container">
        <video id="ra-video" autoplay loop muted playsinline>
            <source src="../static/video/ra.mp4" type="video/mp4">
            Tu navegador no soporta el elemento de video.
        </video>
    </div>
    <div class="footer">
        <div class="nav-item" data-url="{{ url_for('probabilidades.Baja') }}" onclick="navigateTo(this)">
            <i class="fas fa-home"></i>
            <div>Home</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.Mapa') }}" onclick="navigateTo(this)">
            <i class="fas fa-map-marker-alt"></i>
            <div>Maps</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.RA') }}" onclick="navigateTo(this)">
            <i class="fas fa-chart-bar"></i>
            <div>RA</div>
        </div>
    </div>
    
</body>
</html>

FlaskAnuies/templates/probabilidadAlta.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AquAlert - Nivel de Probabilidad de Inundación</title>
    <link rel="stylesheet" href="../static/css/ProbabilidadAlta.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    
    <script>
        function redirectToProbabilidadBaja() {
            window.location.href = "{{ url_for('probabilidades.Baja') }}";
        }
    </script>
    <script>
        function navigateTo(element) {
            const url = element.getAttribute('data-url');
            window.location.href = url;
        }
    </script>
    
</head>
<body>
    <div class="app-header">
        <i class="fas fa-tint"></i>
        AquAlert
    </div>
    <div class="container">
        <div class="header">
            <div class="title">Probabilidad de Inundacion</div>
            
        </div>
        <div class="probability-circle" onclick="redirectToProbabilidadBaja()">
            <div class="probability">93%</div>
        </div>        
        <div class="description">!ALTA PROBABILIDAD DE INUNDACION!</div>
        <div class="section">
            <div class="section">
                <div class="section-title">
                    <i class="fas fa-box-open"></i>
                    <strong>Preparar un Kit de Emergencia</strong>
                </div>
                <div class="section-content">
                    Asegúrate de tener un kit de emergencia con suministros esenciales como agua, comida, medicinas y linterna.
                </div>
            </div>
            <div class="section">
                <div class="section-title">
                    <i class="fas fa-exclamation-triangle"></i>
                    <strong>Evitar Zonas Propensas a Inundaciones</strong>
                </div>
                <div class="section-content">
                    Mantente alejado de áreas bajas y lugares cercanos a ríos y canales que puedan inundarse rápidamente.
                </div>
            </div>
            <div class="section">
                <div class="section-title">
                    <i class="fas fa-route"></i>
                    <strong>Tener un Plan de Evacuación</strong>
                </div>
                <div class="section-content">
                    Conoce las rutas de evacuación y ten un plan claro para salir de la zona de riesgo en caso de emergencia.
                </div>
            </div>
            
        
    </div>
    <div class="footer">
        <div class="nav-item" data-url="{{ url_for('probabilidades.Baja') }}" onclick="navigateTo(this)">
            <i class="fas fa-home"></i>
            <div>Home</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.Mapa') }}" onclick="navigateTo(this)">
            <i class="fas fa-map-marker-alt"></i>
            <div>Maps</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.RA') }}" onclick="navigateTo(this)">
            <i class="fas fa-chart-bar"></i>
            <div>RA</div>
        </div>
    </div>
    
</body>
</html>

FlaskAnuies/templates/probabilidadBaja.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AquAlert - Nivel de Probabilidad de Inundación</title>
    <link rel="stylesheet" href="../static/css/ProbabilidadBaja.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    <script>
        function redirectToProbabilidadMedia() {
            window.location.href = "{{ url_for('probabilidades.Media') }}";
        }
    </script>
    <script>
        function navigateTo(element) {
            const url = element.getAttribute('data-url');
            window.location.href = url;
        }
    </script>
    
</head>
<body>
    <div class="app-header">
        <i class="fas fa-tint"></i>
        AquAlert
    </div>
    <div class="container">
        <div class="header">
            <div class="title">Probabilidad de Inundacion</div>
            
        </div>
        <div class="probability-circle" onclick="redirectToProbabilidadMedia()">
            <div class="probability">5%</div>
        </div>
        <div class="description">Baja Probabilidad de inundacion.</div>
        <div class="section">
            <div class="section-title">
                <i class="fas fa-smile"></i>
                <strong>Disfruta de Tu Día</strong>
            </div>
            <div class="section-content">
                Aprovecha el buen clima para realizar tus actividades cotidianas sin preocupaciones.
            </div>
        </div>
        <div class="section">
            <div class="section-title">
                <i class="fas fa-cloud-sun"></i>
                <strong>Verifica los Pronósticos Ocasionalmente</strong>
            </div>
            <div class="section-content">
                Revisa el pronóstico del tiempo una vez al día para estar informado de cualquier cambio.
            </div>
        </div>
        <div class="section">
            <div class="section-title">
                <i class="fas fa-phone-alt"></i>
                <strong>Mantén tus Canales de Comunicación Abiertos</strong>
            </div>
            <div class="section-content">
                Asegúrate de que tu teléfono esté cargado y que puedas recibir notificaciones en caso de emergencias.
            </div>
        </div>
        
    </div>
    <div class="footer">
        <div class="nav-item" data-url="{{ url_for('probabilidades.Baja') }}" onclick="navigateTo(this)">
            <i class="fas fa-home"></i>
            <div>Home</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.Mapa') }}" onclick="navigateTo(this)">
            <i class="fas fa-map-marker-alt"></i>
            <div>Maps</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.RA') }}" onclick="navigateTo(this)">
            <i class="fas fa-chart-bar"></i>
            <div>RA</div>
        </div>
    </div>
    
</body>
</html>

FlaskAnuies/templates/probabilidadMedia.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AquAlert - Nivel de Probabilidad de Inundación</title>
    <link rel="stylesheet" href="../static/css/ProbabilidadMedia.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    
    <script>
        function redirectToProbabilidadAlta() {
            window.location.href = "{{ url_for('probabilidades.Alta') }}";
        }
    </script>
    <script>
        function navigateTo(element) {
            const url = element.getAttribute('data-url');
            window.location.href = url;
        }
    </script>
    
</head>
<body>
    <div class="app-header">
        <i class="fas fa-tint"></i>
        AquAlert
    </div>
    <div class="container">
        <div class="header">
            <div class="title">Probabilidad de Inundacion</div>
            
        </div>
        <div class="probability-circle" onclick="redirectToProbabilidadAlta()">
            <div class="probability">56%</div>
        </div>        
        <div class="description">Media Probabilidad de inundacion.</div>
        <div class="section">
            <div class="section-title">
                <i class="fas fa-check-circle"></i>
                <strong>Monitorar el Clima Regularmente</strong>
            </div>
            <div class="section-content">
                Revisa las actualizaciones meteorológicas cada pocas horas.
            </div>
        </div>
        <div class="section">
            <div class="section-title">
                <i class="fas fa-map-marker-alt"></i>
                <strong>Revisar el Mapa de Áreas Seguras</strong>
            </div>
            <div class="section-content">
                Verifica el mapa para localizar los puntos de reunión más cercanos y rutas de evacuación.
            </div>
        </div>
        <div class="section">
            <div class="section-title">
                <i class="fas fa-water"></i>
                <strong>Asegurarse de que los Drenajes estén Despejados</strong>
            </div>
            <div class="section-content">
                Mantén los drenajes y canales de agua despejados para evitar acumulaciones de agua.
            </div>
        </div>
        
        
    </div>
    <div class="footer">
        <div class="nav-item" data-url="{{ url_for('probabilidades.Baja') }}" onclick="navigateTo(this)">
            <i class="fas fa-home"></i>
            <div>Home</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.Mapa') }}" onclick="navigateTo(this)">
            <i class="fas fa-map-marker-alt"></i>
            <div>Maps</div>
        </div>
        <div class="nav-item" data-url="{{ url_for('probabilidades.RA') }}" onclick="navigateTo(this)">
            <i class="fas fa-chart-bar"></i>
            <div>RA</div>
        </div>
    </div>
    
</body>
</html>